/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sms_app_interphone_util_aesutil_SMSEncrypt */

#ifndef _Included_com_sms_app_interphone_util_aesutil_SMSEncrypt
#define _Included_com_sms_app_interphone_util_aesutil_SMSEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sms_app_interphone_util_aesutil_SMSEncrypt
 * Method:    aes_init
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sms_app_interphone_util_aesutil_SMSEncrypt_aes_1init
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_sms_app_interphone_util_aesutil_SMSEncrypt
 * Method:    aes_encode
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_sms_app_interphone_util_aesutil_SMSEncrypt_aes_1encode
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_sms_app_interphone_util_aesutil_SMSEncrypt
 * Method:    aes_decode
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_sms_app_interphone_util_aesutil_SMSEncrypt_aes_1decode
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_sms_app_interphone_util_aesutil_SMSEncrypt
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sms_app_interphone_util_aesutil_SMSEncrypt_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
