/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ys_androidapplication_util_voiceutil_voice_Speex */

#ifndef _Included_com_sms_app_interphone_util_voiceutil_voice_Speex
#define _Included_com_sms_app_interphone_util_voiceutil_voice_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sms_app_interphone_util_voiceutil_voice_Speex_DEFAULT_COMPRESSION
#define com_sms_app_interphone_util_voiceutil_voice_Speex_DEFAULT_COMPRESSION 4L
/*
 * Class:     com_sms_app_interphone_util_voiceutil_voice_Speex
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sms_app_interphone_util_voiceutil_voice_Speex_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sms_app_interphone_util_voiceutil_voice_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sms_app_interphone_util_voiceutil_voice_Speex_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     com_sms_app_interphone_util_voiceutil_voice_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_com_sms_app_interphone_util_voiceutil_voice_Speex_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     com_sms_app_interphone_util_voiceutil_voice_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_sms_app_interphone_util_voiceutil_voice_Speex_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     com_sms_app_interphone_util_voiceutil_voice_Speex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sms_app_interphone_util_voiceutil_voice_Speex_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
